### ISSUE TITLE
NoMethodError: undefined method `now' for nil:NilClass

### ISSUE THREAD

**Issue by volkerholloh** [simplymadeapps/simple_scheduler#9]
Hi there,

thank you for your work on this nice gem. :)

I am sorry to report that I was not able to get it going.

Here is the output at the terminal after I ran "rake simple_scheduler --trace"

```
/Users/volker/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/simple_scheduler-0.2.4/lib/simple_scheduler/at.rb:72:in `now'
/Users/volker/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/simple_scheduler-0.2.4/lib/simple_scheduler/at.rb:76:in `parsed_day'
/Users/volker/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/simple_scheduler-0.2.4/lib/simple_scheduler/at.rb:92:in `parsed_time'
/Users/volker/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/simple_scheduler-0.2.4/lib/simple_scheduler/at.rb:28:in `initialize'
/Users/volker/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/simple_scheduler-0.2.4/lib/simple_scheduler/task.rb:31:in `new'
/Users/volker/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/simple_scheduler-0.2.4/lib/simple_scheduler/task.rb:31:in `at'
/Users/volker/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/simple_scheduler-0.2.4/lib/simple_scheduler/task.rb:67:in `future_run_times'
/Users/volker/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/simple_scheduler-0.2.4/lib/simple_scheduler/scheduler_job.rb:28:in `block in queue_future_jobs'
/Users/volker/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/simple_scheduler-0.2.4/lib/simple_scheduler/scheduler_job.rb:26:in `each'
/Users/volker/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/simple_scheduler-0.2.4/lib/simple_scheduler/scheduler_job.rb:26:in `queue_future_jobs'
/Users/volker/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/simple_scheduler-0.2.4/lib/simple_scheduler/scheduler_job.rb:9:in `perform'
/Users/volker/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/activejob-5.0.0.1/lib/active_job/execution.rb:34:in `block in perform_now'
/Users/volker/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:126:in `call'
/Users/volker/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:126:in `call'
/Users/volker/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:506:in `block (2 levels) in compile'
/Users/volker/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:455:in `call'
/Users/volker/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:455:in `call'
/Users/volker/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:448:in `block (2 levels) in around'
/Users/volker/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:286:in `call'
/Users/volker/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:286:in `block (2 levels) in halting'
/Users/volker/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/newrelic_rpm-3.17.0.325/lib/new_relic/agent/transaction.rb:108:in `wrap'
/Users/volker/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/newrelic_rpm-3.17.0.325/lib/new_relic/agent/instrumentation/active_job.rb:59:in `run_in_transaction'
/Users/volker/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/newrelic_rpm-3.17.0.325/lib/new_relic/agent/instrumentation/active_job.rb:48:in `perform'
/Users/volker/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/newrelic_rpm-3.17.0.325/lib/new_relic/agent/instrumentation/active_job.rb:20:in `block (3 levels) in <top (required)>'
/Users/volker/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:391:in `instance_exec'
/Users/volker/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:391:in `block in make_lambda'
/Users/volker/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:285:in `call'
/Users/volker/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:285:in `block in halting'
/Users/volker/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:447:in `call'
/Users/volker/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:447:in `block in around'
/Users/volker/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:455:in `call'
/Users/volker/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:455:in `call'
/Users/volker/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:448:in `block (2 levels) in around'
/Users/volker/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:286:in `call'
/Users/volker/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:286:in `block (2 levels) in halting'
/Users/volker/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/i18n-0.7.0/lib/i18n.rb:257:in `with_locale'
/Users/volker/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/activejob-5.0.0.1/lib/active_job/translation.rb:7:in `block (2 levels) in <module:Translation>'
/Users/volker/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:391:in `instance_exec'
/Users/volker/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:391:in `block in make_lambda'
/Users/volker/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:285:in `call'
/Users/volker/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:285:in `block in halting'
/Users/volker/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:447:in `call'
/Users/volker/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:447:in `block in around'
/Users/volker/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:455:in `call'
/Users/volker/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:455:in `call'
/Users/volker/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:448:in `block (2 levels) in around'
/Users/volker/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:286:in `call'
/Users/volker/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:286:in `block (2 levels) in halting'
/Users/volker/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/activejob-5.0.0.1/lib/active_job/logging.rb:24:in `call'
/Users/volker/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/activejob-5.0.0.1/lib/active_job/logging.rb:24:in `block (4 levels) in <module:Logging>'
/Users/volker/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/activesupport-5.0.0.1/lib/active_support/notifications.rb:164:in `block in instrument'
/Users/volker/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/activesupport-5.0.0.1/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
/Users/volker/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/activesupport-5.0.0.1/lib/active_support/notifications.rb:164:in `instrument'
/Users/volker/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/activejob-5.0.0.1/lib/active_job/logging.rb:23:in `block (3 levels) in <module:Logging>'
/Users/volker/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/activejob-5.0.0.1/lib/active_job/logging.rb:44:in `block in tag_logger'
/Users/volker/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/activesupport-5.0.0.1/lib/active_support/tagged_logging.rb:70:in `block in tagged'
/Users/volker/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/activesupport-5.0.0.1/lib/active_support/tagged_logging.rb:26:in `tagged'
/Users/volker/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/activesupport-5.0.0.1/lib/active_support/tagged_logging.rb:70:in `tagged'
/Users/volker/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/activejob-5.0.0.1/lib/active_job/logging.rb:44:in `tag_logger'
/Users/volker/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/activejob-5.0.0.1/lib/active_job/logging.rb:20:in `block (2 levels) in <module:Logging>'
/Users/volker/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:391:in `instance_exec'
/Users/volker/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:391:in `block in make_lambda'
/Users/volker/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:285:in `call'
/Users/volker/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:285:in `block in halting'
/Users/volker/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:447:in `call'
/Users/volker/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:447:in `block in around'
/Users/volker/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:455:in `call'
/Users/volker/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:455:in `call'
/Users/volker/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:101:in `__run_callbacks__'
/Users/volker/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:750:in `_run_perform_callbacks'
/Users/volker/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:90:in `run_callbacks'
/Users/volker/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/activejob-5.0.0.1/lib/active_job/execution.rb:33:in `perform_now'
/Users/volker/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/activejob-5.0.0.1/lib/active_job/execution.rb:16:in `perform_now'
/Users/volker/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/simple_scheduler-0.2.4/lib/tasks/simple_scheduler_tasks.rake:3:in `block in <top (required)>'
/Users/volker/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/rake-11.3.0/lib/rake/task.rb:248:in `call'
/Users/volker/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/rake-11.3.0/lib/rake/task.rb:248:in `block in execute'
/Users/volker/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/rake-11.3.0/lib/rake/task.rb:243:in `each'
/Users/volker/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/rake-11.3.0/lib/rake/task.rb:243:in `execute'
/Users/volker/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/rake-11.3.0/lib/rake/task.rb:187:in `block in invoke_with_call_chain'
/Users/volker/.rbenv/versions/2.2.4/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
/Users/volker/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/rake-11.3.0/lib/rake/task.rb:180:in `invoke_with_call_chain'
/Users/volker/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/rake-11.3.0/lib/rake/task.rb:173:in `invoke'
/Users/volker/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/rake-11.3.0/lib/rake/application.rb:152:in `invoke_task'
/Users/volker/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/rake-11.3.0/lib/rake/application.rb:108:in `block (2 levels) in top_level'
/Users/volker/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/rake-11.3.0/lib/rake/application.rb:108:in `each'
/Users/volker/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/rake-11.3.0/lib/rake/application.rb:108:in `block in top_level'
/Users/volker/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/rake-11.3.0/lib/rake/application.rb:117:in `run_with_threads'
/Users/volker/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/rake-11.3.0/lib/rake/application.rb:102:in `top_level'
/Users/volker/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/rake-11.3.0/lib/rake/application.rb:80:in `block in run'
/Users/volker/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/rake-11.3.0/lib/rake/application.rb:178:in `standard_exception_handling'
/Users/volker/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/rake-11.3.0/lib/rake/application.rb:77:in `run'
/Users/volker/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/rake-11.3.0/exe/rake:27:in `<top (required)>'
/Users/volker/.rbenv/versions/2.2.4/bin/rake:23:in `load'
/Users/volker/.rbenv/versions/2.2.4/bin/rake:23:in `<main>'
```

My simple_scheduler.yml
```
# Global configuration options and their defaults. These can also be set on each task.
queue_ahead: 360 # Number of minutes to queue jobs into the future
tz: nil # The application time zone will be used by default

# Runs once every minute
simple_task:
  class: "CheckForAlarmsJob"
  every: "2.minutes"

# https://github.com/simplymadeapps/simple_scheduler
```

My job:
```
class CheckForAlarmsJob < ApplicationJob
  queue_as :default

  def perform(scheduled_time)
    # Do something later
    # Rails.logger.info("Job CheckForAlarms running: #{Time.now}")
    puts Time.at(scheduled_time)

  end
end
```

Any help is appreciated.

Cheers,
Volker

**Comment by brianpattison** [comment]
@volkerholloh Hmmm... that's definitely not expected. One thing you might want to try is explicitly setting the time zone using the `tz` configuration option. If you just want to try to get it working by adding a time zone:

```yml
# change:
tz: nil

# to:
tz: "Europe/Berlin" # or any IANA time zone
```

That still doesn't explain why it doesn't fall back to the application's time zone.

Can you jump into your Rails console and tell me what `Time.zone` returns for you? That's what I'm falling back to if you don't specify, so I'm wondering why it be returning `nil`.

If `Time.zone` is returning `nil`, I'll know that I can't rely on it as the fallback. If it's returning an `ActiveSupport::TimeZone`, I guess I have some more investigating to do.

**Comment by volkerholloh** [comment]
Hello Brian,

my rails console:
irb(main):001:0> Time.zone
=> #<ActiveSupport::TimeZone:0x007fcc9cfbec10 @name="UTC", @utc_offset=nil, @tzinfo=#<TZInfo::DataTimezone: Etc/UTC>>
irb(main):002:0>

After I changed to 
# to:
tz: "Europe/Berlin" # or any IANA time zone

it seems to work:
rake simple_scheduler --trace
** Invoke simple_scheduler (first_time)
** Invoke environment (first_time)
** Execute environment
** Execute simple_scheduler

Sp, maybe UTC is the culprit?

Thanks again!
Volker

**Comment by brianpattison** [comment]
@volkerholloh It was actually a bug in the code, so thanks for your help discovering it! It will really help others who copy/paste the sample config code to get started.
